//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCCD
    {
        public int ID_CCCD { get; set; }
        public Nullable<int> ID_CongDan { get; set; }
        public string SoCCCD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
    
        public virtual CongDan CongDan { get; set; }

        public CCCD(int ID_CCCD, int? ID_CongDan, string SoCCCD, DateTime? NgayCap, string NoiCap)
        {
            this.ID_CCCD = ID_CCCD;
            this.ID_CongDan = ID_CongDan;
            this.SoCCCD = SoCCCD;
            this.NgayCap = NgayCap;
            this.NoiCap = NoiCap;
        }
        public CCCD(int? ID_CongDan, string SoCCCD, DateTime? NgayCap, string NoiCap)
        {
            this.ID_CongDan = ID_CongDan;
            this.SoCCCD = SoCCCD;
            this.NgayCap = NgayCap;
            this.NoiCap = NoiCap;
        }
        public CCCD() { }
    }
}
