//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTy_NhanVien
    {
        public int ID_CongTyNhanVien { get; set; }
        public Nullable<int> ID_CongTy { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayVao { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        public virtual CongTy CongTy { get; set; }
    }
}
