//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongDan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongDan()
        {
            this.CCCDs = new HashSet<CCCD>();
            this.CongDan_SoHoKhau = new HashSet<CongDan_SoHoKhau>();
            this.CongTy_NhanVien = new HashSet<CongTy_NhanVien>();
            this.HonNhans = new HashSet<HonNhan>();
            this.HonNhans1 = new HashSet<HonNhan>();
            this.KhaiSinhs = new HashSet<KhaiSinh>();
            this.KhaiSinhs1 = new HashSet<KhaiSinh>();
            this.KhaiSinhs2 = new HashSet<KhaiSinh>();
            this.KhaiSinhs3 = new HashSet<KhaiSinh>();
            this.KhaiTus = new HashSet<KhaiTu>();
            this.KhaiTus1 = new HashSet<KhaiTu>();
            this.LichSuThues = new HashSet<LichSuThue>();
            this.TamTruTamVangs = new HashSet<TamTruTamVang>();
        }

        public CongDan(string HoTen, string QueQuan, string GioiTinh, DateTime NgaySinh, string danToc, string tonGiao, string SDT, string email, string noiThuongTru, string quocTich)
        {
            this.HoTen = HoTen;
            this.QueQuan = QueQuan;
            this.GioiTinh = GioiTinh;
            this.NgaySinh = NgaySinh;
            this.DanToc = DanToc;
            this.TonGiao = TonGiao;
            this.SDT = SDT;
            this.Email = Email;
            this.NoiThuongTru = NoiThuongTru;
            this.QuocTich = QuocTich;


        }

        public CongDan(string iD_CongDan ,string HoTen, string QueQuan, string GioiTinh, DateTime NgaySinh, string danToc, string tonGiao, string SDT, string email, string noiThuongTru, string quocTich)
        {
            this.ID_CongDan = int.Parse(iD_CongDan);
            this.HoTen = HoTen;
            this.QueQuan = QueQuan;
            this.GioiTinh = GioiTinh;
            this.NgaySinh = NgaySinh;
            this.DanToc = DanToc;
            this.TonGiao = TonGiao;
            this.SDT = SDT;
            this.Email = Email;
            this.NoiThuongTru = NoiThuongTru;
            this.QuocTich = QuocTich;
        }

        public CongDan(int iD_CongDan, string hoTen, string quocTich, string queQuan, string gioiTinh, DateTime? ngaySinh, string danToc, string tonGiao, string sDT, string email, string noiThuongTru, string noiSinh)
        {
            ID_CongDan = iD_CongDan;
            HoTen = hoTen;
            QuocTich = quocTich;
            QueQuan = queQuan;
            GioiTinh = gioiTinh;
            NgaySinh = ngaySinh;
            DanToc = danToc;
            TonGiao = tonGiao;
            SDT = sDT;
            Email = email;
            NoiThuongTru = noiThuongTru;
            NoiSinh = noiSinh;
        }

        public int ID_CongDan { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string NoiSinh { get; set; }
        public string NoiThuongTru { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string QuocTich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCCD> CCCDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongDan_SoHoKhau> CongDan_SoHoKhau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongTy_NhanVien> CongTy_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HonNhan> HonNhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HonNhan> HonNhans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiSinh> KhaiSinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiSinh> KhaiSinhs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiSinh> KhaiSinhs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiSinh> KhaiSinhs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiTu> KhaiTus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiTu> KhaiTus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThue> LichSuThues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamTruTamVang> TamTruTamVangs { get; set; }
    }
}
