//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTy_NhanVien
    {
        public CongTy_NhanVien(int iD_CongTy, int iD_CongDan, long Luong)
        {
            ID_CongTy = iD_CongTy;
            ID_NhanVien = iD_CongDan;
            this.Luong = Luong;
            NgayVao = DateTime.Now;
            TrangThai = true;
        }

        public CongTy_NhanVien(int iD_CongTyNhanVien, int? iD_CongTy, int? iD_NhanVien, DateTime? ngayVao, bool? trangThai, decimal? luong)
        {
            ID_CongTyNhanVien = iD_CongTyNhanVien;
            ID_CongTy = iD_CongTy;
            ID_NhanVien = iD_NhanVien;
            NgayVao = ngayVao;
            TrangThai = trangThai;
            Luong = luong;
        }

        public int ID_CongTyNhanVien { get; set; }
        public Nullable<int> ID_CongTy { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayVao { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        public virtual CongTy CongTy { get; set; }
    }
}
