//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongDan_SoHoKhau
    {
        public int ID_SoHoKhau { get; set; }
        public int ID_CongDan { get; set; }
        public string QuanHe { get; set; }
        public string NgheNghiep_NoiLamViec { get; set; }
        public string NoiThuongTruTruoc { get; set; }
        public string CanBoDangKy { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        public virtual SoHoKhau SoHoKhau { get; set; }
    }
}
