//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HonNhan
    {
        public int ID_HonNhan { get; set; }
        public Nullable<int> ID_Chong { get; set; }
        public Nullable<int> ID_Vo { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string NoiDangKy { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        public virtual CongDan CongDan1 { get; set; }
    }
}
