//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaiTu
    {
        public KhaiTu()
        {
        }

        public KhaiTu(int iD_KhaiTu, int? iD_CongDan, int? iD_NguoiYeuCau, string quanHe, DateTime? thoiGianChet, string noiChet, string nguyenNhan, string noiDangKy, DateTime? ngayThucHien)
        {
            ID_KhaiTu = iD_KhaiTu;
            ID_CongDan = iD_CongDan;
            ID_NguoiYeuCau = iD_NguoiYeuCau;
            QuanHe = quanHe;
            ThoiGianChet = thoiGianChet;
            NoiChet = noiChet;
            NguyenNhan = nguyenNhan;
            NoiDangKy = noiDangKy;
            NgayThucHien = ngayThucHien;
        }

        public int ID_KhaiTu { get; set; }
        public Nullable<int> ID_CongDan { get; set; }
        public Nullable<int> ID_NguoiYeuCau { get; set; }
        public string QuanHe { get; set; }
        public Nullable<System.DateTime> ThoiGianChet { get; set; }
        public string NoiChet { get; set; }
        public string NguyenNhan { get; set; }
        public string NoiDangKy { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
    
        public virtual CongDan CongDan { get; set; }
        public virtual CongDan CongDan1 { get; set; }
    }
}
