//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoHoKhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoHoKhau()
        {
            this.CongDan_SoHoKhau = new HashSet<CongDan_SoHoKhau>();
        }

        public SoHoKhau(int iD_SoHoKhau, int? iD_HoSoHoKhau, string iD_SoDangKyThuongTru, string iD_SoDangKyThuongTru_ToSo, string noiThuongTru, DateTime? ngayDangKy)
        {
            ID_SoHoKhau = iD_SoHoKhau;
            ID_HoSoHoKhau = iD_HoSoHoKhau;
            ID_SoDangKyThuongTru = iD_SoDangKyThuongTru;
            ID_SoDangKyThuongTru_ToSo = iD_SoDangKyThuongTru_ToSo;
            NoiThuongTru = noiThuongTru;
            NgayDangKy = ngayDangKy;
        }

        public int ID_SoHoKhau { get; set; }
        public Nullable<int> ID_HoSoHoKhau { get; set; }
        public string ID_SoDangKyThuongTru { get; set; }
        public string ID_SoDangKyThuongTru_ToSo { get; set; }
        public string NoiThuongTru { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongDan_SoHoKhau> CongDan_SoHoKhau { get; set; }
    }
}
