//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TamTruTamVang
    {
        public int ID_TamTru { get; set; }
        public Nullable<int> ID_CongDan { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public string DiaChi { get; set; }
        public string LiDo { get; set; }
    
        public virtual CongDan CongDan { get; set; }
    }
}
